### ISSUE TITLE
2.0.29: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [cminyard/openipmi#2]
It is continuation of the https://sourceforge.net/p/openipmi/feature-requests/9/

I have those undefined symbols because I'm building all my binaries with LTO which is causing that all public symbols of DSO are not placed in the actual public ABI interface as they are not explicit listed that exact symbol should be placed in ABI of the generated DSO. LTO simple discards all that code.
Solutions:
- add in each library linking options linker script which will have listed all publically exprted symbols
- add in C code `__attribute__ ((visibility ("<symbol>")))` https://gcc.gnu.org/wiki/Visibility

In this cases however it looks like it could be yet another issue that test suite is using symbol which is used probably only by test suite (because I don't see any issues with OpenIMPI binaries linked with LTO).

**Comment by cminyard** [comment]
On Sat, Jun 27, 2020 at 12:29:49PM -0700, Tomasz Kłoczko wrote:
> It is continuation of the https://sourceforge.net/p/openipmi/feature-requests/9/
> 
> I have those undefined symbols because I'm building all my binaries with LTO which is causing that all public symbols of DSO are not placed in the actual public ABI interface as they are not explicit listed that exact symbol should be placed in ABI of the generated DSO. LTO simple discards all that code.
> Solutions:
> - add in each library linking options linker script which will have listed all publically exprted symbols
> - add in C code `__attribute__ ((visibility ("<symbol>")))` https://gcc.gnu.org/wiki/Visibility
> 
> In this cases however it looks like it could be yet another issue that test suite is using symbol which is used probably only by test suite (because I don't see any issues with OpenIMPI binaries linked with LTO).

Ah I forgot about LTO.  Sorry.

It's not the test suite, it's the swig perl library where the issue
lies.  So unless you did something with perl or python, you wouldn't see
this particular problem.  The cmdlang library requires the user to
define the specific function that is failing, and in this case it's
defined in the swig based library.

So if I add

#pragma GCC visibility push(default)
#pragma GCC visibility pop

around the definition of that function, or add
__attribute__ ((visibility ("default")))
in front of the extern function definition, it should work ok.

The trouble with the latter is compiling on non-gcc or older gcc
systems.  I see a bunch of preprocessor code to handle this.

-corey

**Comment by cminyard** [comment]
I think this is all fixed now.  It actually got fixed as part of compiling for DLLs on windows, but it's the same basic issue.

**Comment by kloczek** [comment]
Q: is this repo now is OpenIIPMI primary repo or not?

**Comment by cminyard** [comment]
On Fri, Sep 03, 2021 at 01:37:07AM -0700, Tomasz Kłoczko wrote:
> Q: is this repo now is OpenIIPMI primary repo or not?

I keep this and the sourceforge one up to date.  I created this primarily
so I could do static analysis on OpenIPMI.

-corey

**Comment by kloczek** [comment]
So looks like this repo is no longer synced.
Last change here was  2021-05-12, and in https://sourceforge.net/p/openipmi/code/commit_browser last change was  2021-07-05.

**Comment by kloczek** [comment]
BTW IMO it would better to switch to github as promary repo because sf.net interface does not allow download patch of exact commit (sf is more and more crappy)

**Comment by cminyard** [comment]
On Fri, Sep 03, 2021 at 03:38:47PM -0700, Tomasz Kłoczko wrote:
> So looks like this repo is no longer synced.
> Last change here was  2021-05-12, and in https://sourceforge.net/p/openipmi/code/commit_browser last change was  2021-07-05.
> 

Yes, I forgot to push to github.  I just did that.

-corey

**Comment by cminyard** [comment]
On Fri, Sep 03, 2021 at 03:40:34PM -0700, Tomasz Kłoczko wrote:
> BTW IMO it would better to switch to github as promary repo because sf.net interface does not allow download patch of exact commit (sf is more and more crappy)

You are right, I know.  I still do tarball releases of OpenIPMI, and
github doesn't have an easy way to do that that I know of.  I know you
can make tarballs from git commits, but that's not ideal for me.

I will probably have to switch over to github at some point in time, but
OpenIPMI is lower priority for me.

-corey

**Comment by kloczek** [comment]
- It is possible to store dist tar ball in git repo look on https://github.com/SELinuxProject/selinux/releases/tag/3.2
- it is possible to sign exact tag and commits https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification
