### ISSUE TITLE
RFE: is it possible to start making github releases?🤔

### ISSUE THREAD

**Issue by kloczek** [cminyard/openipmi#6]
On create github release entry is created email notification to those whom have set in your repo the web UI Watch->Releases.
gh release can contain additional comments (li changelog) or additional assets like release tar balls (by default it contains only assets from git tag) however all those part are not obligatory.
In simplest variant gh release can be empty because subiekt of the sent email contains git tag name.

I'm asking because my automation process uses those email notifications by trying to make preliminary automated upgrades of building packages, which allows saving some time on maintaining packaging procedures.
Probably other people may be interested to be instantly informed about release new version as well.

Documentation and examples of generate gh releases:
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://cli.github.com/manual/gh_release_upload/
https://github.com/jbms/sphinx-immaterial/pull/282
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/
https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026
tox target to publish on pypi and make gh release https://github.com/jaraco/skeleton/blob/928e9a86d61d3a660948bcba7689f90216cc8243/tox.ini#L42-L58

**Comment by cminyard** [comment]
On Wed, Feb 14, 2024 at 01:47:56AM -0800, Tomasz Kłoczko wrote:
> On create github release entry is created email notification to those whom have set in your repo the web UI Watch->Releases.
> gh release can contain additional comments (li changelog) or additional assets like release tar balls (by default it contains only assets from git tag) however all those part are not obligatory.
> In simplest variant gh release can be empty because subiekt of the sent email contains git tag name.
> 
> I'm asking because my automation process uses those email notifications by trying to make preliminary automated upgrades of building packages, which allows saving some time on maintaining packaging procedures.
> Probably other people may be interested to be instantly informed about release new version as well.


Yeah, I know how to generate github releases, but I haven't done it for
openipmi because it's really just there to allow me to scan it with
coverity.  I do announcements on sourceforge, but I'm not sure how many
people look there an more.

I can try to do this, but it will be hard for me to remember.

**Comment by kloczek** [comment]
> I can try to do this, but it will be hard for me to remember.

This is why it is sometimes better to automate that 😋 
Nevertheless thank you for your time 👍 😄

**Comment by cminyard** [comment]
I'm starting to make github releases now.

**Comment by kloczek** [comment]
Thank you 😄 👍
